Adding services and in memory test data
ivozhel/BookStore pull request #2
Opened 2022-09-30 14:46 UTC by ivozhel

2022-10-01 05:03 UTC, sabazius requested changes

2022-10-01 06:15 UTC, ivozhel commented on BookStore/BookStore.BL/Services/AuthorService.cs
> +    public class AuthorService : AuthorInMemoryRepo, IAuthorService
разбрах че ни липсва бизнес логика за примера и за да спестя писане на същите методи наследих Repo класовете (в реален кейс няма да е така)

2022-10-01 06:15 UTC, ivozhel commented on BookStore/BookStore.DL/Repositories/InMemoryRepos/PersonInMemoryRepo.cs
> +    public class PersonInMemoryRepo:IPersonRepo
Ок

2022-10-01 06:16 UTC, ivozhel commented on BookStore/BookStore/Controllers/BookController.cs
> +        private readonly IBookService _BookRepo;
Ок

2022-10-01 09:12 UTC, sabazius commented on BookStore/BookStore.BL/Services/AuthorService.cs
> +    public class AuthorService : AuthorInMemoryRepo, IAuthorService
да, те на практика са еднакви, но по-добре да са раделени. Ако искаш го остави, но като започнеш работа в екип ще трябва да си ги разделяш.

2022-10-03 06:23 UTC, sabazius approved these changes

2022-10-03 06:27 UTC, merged